---
title: "Installation"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

[`git`]: https://git-scm.com/downloads
[`rss`]: https://github.com/stephenslab/rss
[`rss-net`]: https://github.com/SUwonglab/rss-net
[`rss/src_vb/install.m`]: https://github.com/stephenslab/rss/blob/master/src_vb/install.m

This page shows how to install the RSS-NET software.
In a standard computing environment with internet connection,
the installation time is typically less than 10 minutes.

## Step-by-step guide

### 0. Install [`git`][] (optional)

To simplify Steps 1-2 below, you may consider
installing [`git`][] in your computing environment
(if it is not available there).
Please see this [excellent tutorial](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git)
on installing [`git`][].

Please note that RSS-NET software does not depend on [`git`][].
You can complete Steps 1-2 without installing [`git`][].

### 1. Clone [`rss`][] repository

With [`git`][] installed, you can easily clone
[`rss`][] by running the following command in Terminal.

```zsh
git clone git@github.com:stephenslab/rss.git
```

Without [`git`][], you can manually download [`rss`][] as follows.

```zsh
wget https://github.com/stephenslab/rss/archive/master.zip
unzip master.zip
rm master.zip
mv rss-master rss
```

### 2. Clone [`rss-net`][] repository

Similar to Step 1, if [`git`][] is available in your computing environment,
you can easily clone [`rss-net`][] by running the following command in Terminal.

```zsh
git clone git@github.com:SUwonglab/rss-net.git
```

Without [`git`][], you can manually download [`rss-net`][] as follows.

```zsh
wget https://github.com/SUwonglab/rss-net/archive/master.zip
unzip master.zip
rm master.zip
mv rss-net-master rss-net 
```

### 3. Compile [mex](https://www.mathworks.com/help/matlab/ref/mex.html) file

Go to `rss/src_vb` and open MATLAB.

```zsh
cd rss/src_vb
matlab -nodesktop
```

Run [`rss/src_vb/install.m`][] in MATLAB. You may get the following output.

```matlab
>> run install.m
Building with 'gcc'.
MEX completed successfully.
Compilation of MEX files is complete.
```

After successfully running [`rss/src_vb/install.m`][],
you will find a file `rss_varbvsr_update_matlab.mexa64` (in Linux)
in the directory `rss/src_vb`, which is the workhorse for variational Bayes computations.

## Computing environment

Please note that RSS-NET have only been extensively tested in **Linux** systems,
using the **version 9.3.0.713579 (R2017b) of MATLAB for 64-bit Linux**.
If you have any trouble installing RSS-NET,
please open an [issue](https://github.com/SUwonglab/rss-net/issues)
or email me (`xiangzhu[at]stanford.edu`).
To help me better understand your problems,
please provide details of your computing environment.

## MEX files

The most tricky part of this installation
is probably compiling MEX files in MATLAB (Step 3).

Before running [`rss/src_vb/install.m`][],
please make sure that you have the compiler
compatible with your version of MATLAB,
and that you can compile the MEX files in
the tutorials given on the MathWorks website.

In addition, please ensure that you compile and run
the scripts in the same version of MATLAB.
For example, if you have compiled MEX files
using MATLAB Release R2017b, please use the compiled output
`rss_varbvsr_update_matlab.mexa64` only in MATLAB R2017b.

For more information on MEX, please see:

- <http://www.mathworks.com/help/matlab/write-cc-mex-files.html>

- <http://www.mathworks.com/help/matlab/matlab_external/introducing-mex-files.html>

- <http://www.mathworks.com/support/sysreq/previous_releases.html>

